theme: papermod
languageCode: en-US
title: Reactive Resume
baseURL: https://blog.rxresu.me/

params:
  env: production
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  homeInfoParams:
    Title: The Reactive Resume Blog
    Content: Reactive Resume is a free and open source resume builder that's built to make the mundane tasks of creating, updating and sharing your resume as easy as 1, 2, 3. This space is dedicated to sharing tips and tutorials on how to get the most out of your resume.

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

menu:
  main:
    - identifier: search
      name: Search
      url: /search
      weight: 10
    - identifier: app
      name: Go to App
      url: https://rxresu.me
      weight: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON
